### PR TITLE
Enhancements/tglf gk code

### PR DESCRIPTION
**Pull request by bpatel2107**
Added in TGLF as an option for a `GKCode`

- [x] Reads in input files
- [x] Reads in output data
- [x] Added examples
- [x] Added test

### CODE REVIEW

**Comment by bpatel2107** [comment]
@LiamPattinson Does this need to be merged before #67 or should we change this PR to match the new format?

**Comment by LiamPattinson** [comment]
@bpatel2107 Hi Bhavin, I was just finishing up on my pull request today, and only have a couple more unit tests to write. Ideally, I'd like to have my PR merged first, as it's already an enormous change, and it'd be good to have it looked over before adding anything further. It might be tricky to convert this to the new methods, so give me a shout if you need help with anything. Is there a deadline on having these features added?

**Comment by bpatel2107** [comment]
No specific deadline, the relevant people can used this branch if needed. Happy to wait

**Comment by bpatel2107** [comment]
@ZedThree I rebased this branch onto unstable and now it looks like all the of pyro gk_refactor commits are in this PR. Any ideas how to undo this? Should I have merge unstable into this branch instead?

**Comment by ZedThree** [comment]
Either rebasing or merging should really have been fine, I think it's just Github messing up. Looking at the comparison of the two branches shows it just fine: https://github.com/pyro-kinetics/pyrokinetics/compare/unstable...enhancements/tglf_gk_code

I'm going to try switching the base branch from unstable to something else and then back. Apparently this might force Github to update the PR correctly. It will leave a couple of log messages in the PR, but these won't affect anything

**Comment by ZedThree** [comment]
Fixed!

**Comment by ZedThree** [comment]
I've made a start on porting this to the new API: https://github.com/pyro-kinetics/pyrokinetics/blob/tglf_new_api/pyrokinetics/gk_code/GKInputTGLF.py

@bpatel2107 Do you want me to push straight to this branch, or make a PR into here?

I've just done the input reader, not sure if I'll have much more time this week to look at the output side

**Comment by bpatel2107** [comment]
You can push to this branch

**Comment by bpatel2107** [comment]
Superceded by #91

**Pull request closed without merging**
