### PR TITLE
Update gs2.py to fix calculation of eigenvalues in non-wstar_units runs

### PR DESCRIPTION
**Pull request by d7919**
Slightly surprised this wasn't caught in the tests so perhaps there's some motivation to add extra tests?

### CODE REVIEW

**Comment by bpatel2107** [comment]
We can add a test comparing the pyro value to the GS2 value were we manually change it by `sqrt(2)` though I think the the template as `wstar_units = .true.`

**Comment by bpatel2107** [comment]
@mgiacomin looks like you were about 30 minutes too slow

**Review by bpatel2107 — APPROVED** [review]

**Comment by mgiacomin** [comment]
Ah sorry I hadn't seen that David pushed the fix already.

**Comment by bpatel2107** [comment]
When we start storing template files on zenodo or something similar we can create more tests covering these cases but until then I can merge for now

**Pull request merged**
