### PR TITLE
Add lightweight linear CGYRO scan to templates

### PR DESCRIPTION
**Pull request by tomneiser**
Added three lightweight sample folders of ky-scan in `/templates/outputs/CGYRO_linear_scan` for pyroscan object and QLGYRO testing and tutorials. Removed unused files in `/templates/outputs/CGYRO_linear`.

### CODE REVIEW

**Comment by bpatel2107** [comment]
I was able to read this in using so looks good to me. Added it in as an example script, along with the input file in the `CGYRO_linear_scans` directory

```python
from pyrokinetics import Pyro, PyroScan, template_dir
import numpy as np

base_directory = template_dir / "outputs/CGYRO_linear_scan"

gk_file = base_directory / "input.cgyro"

pyro = Pyro(gk_file=gk_file)

param_key = "ky"
param_value = np.array([0.1, 0.2, 0.3])
param_dict = {param_key: param_value}

# Create PyroScan object
pyro_scan = PyroScan(
    pyro,
    param_dict,
    base_directory=base_directory
)

pyro_scan.load_gk_output()

```

**Comment by bpatel2107** [comment]
@tomneiser This looks good. Do you want wait until the QL rules are in properly or are you happy to merge as is?

**Comment by tomneiser** [comment]
I'm happy to merge as is, thanks!

**Review by bpatel2107 — APPROVED** [review]
LGTM

**Pull request merged**
