### PR TITLE
Create CITATION.cff

### PR DESCRIPTION
**Pull request by bpatel2107**
Made a citation file to make it easier to cite this repo.

@ZedThree not sure what the normal convention is here. Do we just add all the contributors to this list? Just put myself for now but happy if people want to add their names to it

### CODE REVIEW

**Comment by bpatel2107** [comment]
Need to make a new release before we get a new zenodo DOI. Not sure if we can make a release on a branch and then have it be the main release when merged

**Comment by ZedThree** [comment]
I would add all contributors, unless there is anybody that wants to be left off.

EDIT: Here's how to quickly list everyone: `git log --format='%aN' | sort | uniq`

**Comment by bpatel2107** [comment]
@ZedThree @fcasson @d7919 @hgd511 @LiamPattinson @ajaycj1 @dake0795 @mgiacomin can you add your ORCID to this if you have one, otherwise remove that line

**Comment by bpatel2107** [comment]
FYI you can get a citation for pyrokinetics on the main page by clicking "Cite this repository" on the right


image

**Comment by fcasson** [comment]
https://orcid.org/0000-0001-5371-5876

**Comment by LiamPattinson** [comment]
Please could you add mine? I don't have the access rights to push to this branch. 

https://orcid.org/0000-0001-8604-6904

**Comment by bpatel2107** [comment]
I added in @ZedThree ORCID, but couldn't find @ajaycj1. Feel free to add your when you get one!

**Comment by ajaycj1** [comment]
@bpatel2107 
Ajay C J: https://orcid.org/0000-0002-6447-581X

**Pull request merged**
