### PR TITLE
Fix incorrect collisionality for ions when Z!=1

### PR DESCRIPTION
**Pull request by bpatel2107**
When setting the collisionality of different ion species from CGYRO/GENE/TGLF, a factor of `Z**4` was missing.

This only impacts results where CGYRO/GENE/TGLF is converted to GS2.  Loading from profile data or a GS2 input file loads in the collisionality correctly. 

Converting between CGYRO/GENE/TGLF would also be fine as this gets the electron collision freq correct and that is what is needed.

### CODE REVIEW

**Comment by ZedThree** [comment]
Please could you add tests? :slightly_smiling_face: 

I wonder if it's worth bringing in plasmapy, which has a [bunch of collision formulas](https://docs.plasmapy.org/en/stable/formulary/collisions.html)

**Comment by bpatel2107** [comment]
Yes I always forget the tests... One day you might not need to remind me

**Comment by LiamPattinson** [comment]
> I wonder if it's worth bringing in plasmapy, which has a [bunch of collision formulas](https://docs.plasmapy.org/en/stable/formulary/collisions.html)

It would be nice to use this so that we didn't have to reinvent the wheel, but since plasmapy uses astropy units, would it not cause issues with our units/normalisations?

**Comment by ZedThree** [comment]
It should be possible to convert between the two libraries -- we'd only be passing physical units, so this should be fine

**Comment by bpatel2107** [comment]
Added tests

**Comment by bpatel2107** [comment]
When we have reference values plasmapy should work but when we don't we'll need to work out how to convert the `gk_code` `nu` to the pyro `nu`

Plasmapy would come in in the `LocalSpecies` class

**Pull request merged**
