### PR TITLE
Enable reading GENE `omega` text file

### PR DESCRIPTION
**Pull request by ZedThree**
Partial fix for #125 

The sample `omega_0001` output file was manually created from the existing sample output. Could a GENE expert check this works with other outputs too?

### CODE REVIEW

**Comment by bpatel2107** [comment]
LGTM. Does this account for #124?

**Comment by ZedThree** [comment]
Nope, that probably needs a GENE expert to check things

**Comment by bpatel2107** [comment]
@dake0795 ?

**Comment by dake0795** [comment]
I believe GENE default Is COCOS=2/12.

**Comment by dake0795** [comment]
Default is that both the plasma current and the toroidal magnetic field are clockwise in a right-handed (ρ, θpol, φtor) coordinate system. Ion diamagnetic direction is positive in the omega_000X file.

**Comment by ZedThree** [comment]
What COCOS do we use in pyrokinetics? ITER/IMAS is 11, right handed $(R, \phi, Z)$ and $(\rho, \theta, \phi)$

**Comment by bpatel2107** [comment]
I _think_ the default pyrokinetics COCOS is 1/11

**Pull request merged**
