### PR TITLE
Bugfix/multiple linear ky

### PR DESCRIPTION
**Pull request by bpatel2107**
This allows for linear runs with multiple `ky` and `kx` to be loaded in pyro as it was previously breaking when trying to normalise/rotate the fields. Addresses #276. Due to this new format, the `growth_rate_tolerance` can now be a function of `ky` and `kx`  so the `GKOutput` format needed to change to accommodate then hence the new test data.

@mehfoos can you see if that works for you?

@LiamPattinson Not sure why tests are failing due to `pyloidal` Was there a recent release?

### CODE REVIEW

**Comment by LiamPattinson** [comment]
We updated Pyloidal yesterday, and moved the `cocos_transform` function to a `Transform` class. If you set `pyloidal == 0.1.0` in `pyproject.toml` it should sort out the problem for now. I'll try to make a PR to update to 0.2.0 later this week.

**Comment by d7919** [comment]
Are the tolerance changes needed here?

**Comment by bpatel2107** [comment]
Well sort of. The changes to calculating via the `xarray` methods are needed to allow for it to be `kx` `ky` dependent. The other change is to bring it inline with the GKDB definition as it was different.

**Review by d7919 — APPROVED** [review]
Looks good to me although I've not had chance to actually test it out yet.

**Comment by bpatel2107** [comment]
Will wait on @mehfoos to confirm but it works for me

**Comment by mehfoos** [comment]
> Will wait on @mehfoos to confirm but it works for me

Thanks for tagging me to check if it's fixed. I'm traveling and will only be able to confirm when I'm back over the weekend, but I'm okay with this being closed if we're fairly confident that it has been fixed. Thank you.

**Comment by mehfoos** [comment]
> Will wait on @mehfoos to confirm but it works for me

Sorry about the delay. Just tried with the test case that had failed in the past, and can confirm that it does work now. Thank you!

**Pull request merged**
