### PR TITLE
Bugfix/update examples

### LINKED ISSUE #28: Most examples don't work
Unfortunately, most of the examples don't run, mostly due to missing templates. Some of them don't work because they need output files -- it's probably worth adding some small output files for those examples, or having the option of downloading them (from e.g. Zenodo) if it's not possible to get them down to a few MB.

I've already modified them to look for the templates directory bundled with pyrokinetics -- PR incoming.

Here's the output from all the non-working examples:

- ./example_addflags.py
```
  nx = 69, ny = 175
501
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_addflags.py", line 13, in <module>
    pyro = Pyro(
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 61, in __init__
    self.read_gk_file()
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 184, in read_gk_file
    self.gk_code.read(self, self.gk_file, template)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gs2.py", line 37, in read
    gs2 = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'myTemplate.gs2'
```
- ./example_cgyro.py
```
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_cgyro.py", line 10, in <module>
    pyro.write_gk_file(file_name="test_cgyro.cgyro")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 212, in write_gk_file
    self.gk_code.write(self, file_name, directory=self.run_directory)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/cgyro.py", line 118, in write
    b_ref = miller.B0 * miller.bunit_over_b0
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```
- ./example_geqdsk.py
```
  nx = 69, ny = 175
501
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_geqdsk.py", line 18, in <module>
    pyro.load_local_geometry(psi_n=0.5)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 241, in load_local_geometry
    raise ValueError("Please specify local geometry type")
ValueError: Please specify local geometry type
```
- ./example_gs2.py
```
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_gs2.py", line 5, in <module>
    pyro = pyrokinetics.Pyro(gk_file=gs2_template, gk_type="GS2")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 61, in __init__
    self.read_gk_file()
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 184, in read_gk_file
    self.gk_code.read(self, self.gk_file, template)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gs2.py", line 37, in read
    gs2 = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: '/home/peter/Codes/pyrokinetics/pyrokinetics/templates/step.in'
```
- ./example_JETTO_1dscan_complicated.py
```
  nx = 69, ny = 175
501
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_JETTO_1dscan_complicated.py", line 25, in <module>
    pyro.write_gk_file(file_name="test_jetto.gs2", template_file="mytemplate.gs2")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 207, in write_gk_file
    self.gk_code.read(self, data_file=template_file, template=True)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gs2.py", line 37, in read
    gs2 = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'mytemplate.gs2'
```
- ./example_JETTO_1dscan.py
```
  nx = 69, ny = 175
501
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_JETTO_1dscan.py", line 25, in <module>
    pyro.write_gk_file(file_name="test_jetto.gs2", template_file="step.in")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 207, in write_gk_file
    self.gk_code.read(self, data_file=template_file, template=True)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gs2.py", line 37, in read
    gs2 = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'step.in'
```
- ./example_JETTO.py
```
  nx = 69, ny = 175
501
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_JETTO.py", line 24, in <module>
    pyro.write_gk_file(file_name="test_jetto.gs2", template_file="step.in")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 207, in write_gk_file
    self.gk_code.read(self, data_file=template_file, template=True)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gs2.py", line 37, in read
    gs2 = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'step.in'
```
- ./example.py
```
  nx = 69, ny = 175
501
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example.py", line 7, in <module>
    geo = pyro.geo
AttributeError: 'Pyro' object has no attribute 'geo'
```
- ./example_read_cgyro_output.py
```
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_read_cgyro_output.py", line 12, in <module>
    pyro.load_gk_output()
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 297, in load_gk_output
    self.gk_code.load_gk_output(self, **kwargs)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/cgyro.py", line 502, in load_gk_output
    self.load_grids(pyro)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/cgyro.py", line 527, in load_grids
    time = np.loadtxt(time_file)[:, 0]
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: /home/peter/Codes/pyrokinetics/pyrokinetics/templates/out.cgyro.time not found.
```
- ./example_read_gene_output.py
```
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_read_gene_output.py", line 9, in <module>
    pyro = Pyro(gk_file=gene_template, gk_type="GENE")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 61, in __init__
    self.read_gk_file()
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 184, in read_gk_file
    self.gk_code.read(self, self.gk_file, template)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gene.py", line 37, in read
    gene = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'parameters_0005'
```
- ./example_read_gs2_output.py
```
Traceback (most recent call last):
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/examples/./example_read_gs2_output.py", line 9, in <module>
    pyro = Pyro(gk_file=gs2_template, gk_type="GS2")
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 61, in __init__
    self.read_gk_file()
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/pyro.py", line 184, in read_gk_file
    self.gk_code.read(self, self.gk_file, template)
  File "/home/peter/Codes/pyrokinetics/pyrokinetics/gs2.py", line 37, in read
    gs2 = f90nml.read(data_file).todict()
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/home/peter/Codes/pyrokinetics/venv/lib64/python3.9/site-packages/f90nml/parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'step_aky_0.5.in'
```

### PR DESCRIPTION
**Pull request by bpatel2107**
Fixes #28 - some examples weren't working

Adds in example linear runs for CGYRO, GENE and GS2 into the templates files

### CODE REVIEW

**Comment by d7919** [comment]
Is there any value in trying to get github actions to build and run the GK codes on some of these as well? I guess this would be complicated for those behind a registration, but it might be possible to build the executables elsewhere and then add those as some sort of artefact for use in the actions run.

**Comment by ZedThree** [comment]
Maybe a docker image with the built codes in? Might be worth contacting the GENE and CGYRO folks if they'd be ok with that. The free dockerhub tier allows one (1) private repo, which would be fine.

**Comment by ZedThree** [comment]
There's a couple of fairly big output files (GENE: 53MB, GS2: 15MB) here. Is it possible to reduce them down a bit?

**Comment by bpatel2107** [comment]
I can do lower resolution GS2 runs. @dake0795 Can you do a lower resolution GENE runs, maybe we can run for like 10 time steps for proof of principle?

**Comment by ZedThree** [comment]
10 time steps would be absolutely plenty for the examples.

**Comment by dake0795** [comment]
Sure, I can do this (but likely not anytime soon since both CSD3 and Marconi are undergoing maintenance today...)

**Comment by bpatel2107** [comment]
Made smaller outputs for each code so it's now (CGYRO: 1.1MB, GS2: 152kB, GENE:1.4MB)

**Comment by bpatel2107** [comment]
Added a basic unit test for the eigenvalues. So far I've got the same case for GS2/CGYRO but not GENE ( I can't run GENE so had to hack together the output).

I'm happy to ask the GENE/CGYRO people about a docker image but for now I'm happy to merge these changes. Set up an issue for this #86

**Comment by bpatel2107** [comment]
@LiamPattinson  I can merge this now if you need it for #67 ?

**Comment by ZedThree** [comment]
Just a note that we should remove the larger files from the repo history: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-files-from-a-repositorys-history

**Comment by LiamPattinson** [comment]
@bpatel2107 There may be some merge issues, as I've made some of my own edits to examples to match the changes I've made, but hopefully nothing major. And as @ZedThree said, it'd be a good idea to remove the large files from the git history first.

**Comment by LiamPattinson** [comment]
Looks good to me!

**Pull request merged**
