### PR TITLE
Add entry-points plugin system + update factories (again)

### PR DESCRIPTION
**Pull request by LiamPattinson**
I've added a plugin system as described in Issue https://github.com/pyro-kinetics/pyrokinetics/issues/256 that allows users to register their own readers for `Equilibrium`/`Kinetics`/`GKInput`/`GKOutput`. These are automatically added to Pyrokinetics if the user's library is installed in the same Python environment.

Testing a plugin system requires the existence of plugins, so I also created a repository of [example plugins](https://github.com/LiamPattinson/pyrokinetics-plugin-examples). This is currently on my personal account, but I can transfer it to the pyro-kinetics organisation if you'd like (thought this might break the PyPI integration -- they've moved away from using API tokens, and instead may require the creation of a pyro-kinetics PyPI organisation). The plugin package is installed if we use `pip install .[tests]` but otherwise isn't included.

Currently I have a test for `Equilibrium` plugins, and I still need to write tests for `Kinetics`, `GKInput`, and `GKOutput`.

---

I also happened across a better way to work with the factory/file reader bits of the code. Currently, you need to use a combination of inheritance and decorators to make a class a 'readable' or a 'reader':

- 'Readables' inherit `ReadableFromFileMixin` to get access to classmethods `from_file`, `supported_file_types`, and `reader`. The `readable_from_file` decorator adds a factory class variable.
- 'Readers' inherit `AbstractFileReader` to get the functions `read_from_file` and `verify_file_type`, and the `Readable.reader` decorator registers them with the readable's factory.

By adding the special method `__init_subclass__` to the two superclasses (renamed `ReadableFromFile` and `FileReader`), we can do away with the decorators and instead use keyword arguments in the class definition:

```python
class GEQDSKReader(FileReader, file_type="GEQDSK", reads=Equilibrium):
    ...
```

Along with simplifying the interface, this also means the code won't run unless you supply the keyword arguments, whereas currently it's possible for users to forget the decorators and end up with subtly broken code.

---

Aside: If you check the `publish.yml` CI job in the plugins package I made, I'm using the new and updated way of publishing to PyPI, plus using TestPyPI to check everything works as expected. I'd like to update Pyrokinetics to do the same, but that can wait for a future PR.

### CODE REVIEW

**Comment by LiamPattinson** [comment]
Unrelated, but I think code cov still isn't working. It seems to only be testing example files in the docs for some reason. I think it might be fixed by adding an empty `__init__.py` to the top-level tests folder and changing the pytest command to `pytest --cov=pyrokinetics --cov-report=xml tests`, but I can play around in a new branch to figure it out. I might be able to merge the tests and coverage workflows while I'm at it too.

**Comment by LiamPattinson** [comment]
I think I have this ready to go now.

**Review by bpatel2107 — APPROVED** [review]
Overall this looks really nice and is a cleaner way to set up `Readers` and `Readables`.

I think keeping the testing plugins separate is better and actually may be worth linking to in the docs to show a `real world` example of how to implement a plugin.

Happy for the publishing to be changed in a future PR

**Comment by LiamPattinson** [comment]
Cheers @bpatel2107. I was planning on making some minor tweaks today, so could we hold off on merging for a day or so? I had a chat with @ZedThree about the separate plugin library, and he had some recommendations to make things a little cleaner.

**Comment by LiamPattinson** [comment]
I think I'm good now. Tweaked the plugin library to escape a potential circular dependency problem and improve its CI, and updated this package so that the plugin tests will simply be skipped if there's a problem importing the plugins. Added a paragraph to the docs like you recommended.

In future, it may be preferable to pin the version of the plugin library to a specific git commit rather than a published version. For example, if future experimental pyrokinetics branches modify something that breaks compatibility with the plugin library, it might not be appropriate to release a new version of the plugin library, but it would instead be possible to pin it to a corresponding experimental plugin branch. It might be a bit fiddly to keep both packages synced up, but hopefully it won't be something we have to touch very often.

**Comment by bpatel2107** [comment]
I don't see the changes to the docs when I load the readthedocs build

https://pyrokinetics--258.org.readthedocs.build/en/258/tutorials/file_readers.html

Something wrong awry? Maybe the build doesn't trigger on changes to `rst` files? Likely fine when merged into unstable...

**Comment by LiamPattinson** [comment]
I'm not sure what's going on there as the changes are there when I open the page. Maybe it just took readthedocs a while to redirect links?

**Comment by bpatel2107** [comment]
Its probably fine

**Pull request merged**
